import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || (typeof window !== 'undefined' && window.location.hostname !== 'localhost' && window.location.hostname !== '127.0.0.1' ? '/api' : 'http://localhost:4000');
const types = ['O-', 'O+', 'A-', 'A+', 'B-', 'B+', 'AB-', 'AB+'];
const api = async (path, options = {}, token) => {
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  const body = await response.json();
  if (!response.ok) throw new Error(body.error || 'Something went wrong.');
  return body;
};
function Badge({ children, tone = 'blue' }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Login({ onLogin }) {
  const [email, setEmail] = useState('admin@centralhospital.demo'); const [password, setPassword] = useState('demo123'); const [error, setError] = useState('');
  async function submit(event) { event.preventDefault(); try { const result = await api('/auth/hospital', { method: 'POST', body: JSON.stringify({ email, password }) }); onLogin(result); } catch (err) { setError(err.message); } }
  return <main className="login-shell"><section className="brand-panel"><div className="mark">+</div><p className="eyebrow">PULSE DIAL / HOSPITAL NETWORK</p><h1>Every second counts.</h1><p>Coordinate verified, nearby donors during critical blood emergencies.</p><div className="signal"><i/><i/><i/><i/><i/></div></section><form className="login-card" onSubmit={submit}><Badge tone="red">SECURE CLINICAL PORTAL</Badge><h2>Sign in to dispatch</h2><p className="muted">Use the demo hospital account to explore the live workflow.</p><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button>Access emergency dashboard →</button><small>Demo credentials are prefilled.</small></form></main>;
}
function NewRequest({ token, onCreated }) {
  const [bloodType, setBloodType] = useState('O-'); const [unitsNeeded, setUnits] = useState(1); const [urgency, setUrgency] = useState('CRITICAL'); const [loading, setLoading] = useState(false);
  async function submit(event) { event.preventDefault(); setLoading(true); try { onCreated(await api('/hospital/requests', { method: 'POST', body: JSON.stringify({ bloodType, unitsNeeded: Number(unitsNeeded), urgency }) }, token)); } finally { setLoading(false); } }
  return <form className="request-form" onSubmit={submit}><div><label>Blood group<select value={bloodType} onChange={e => setBloodType(e.target.value)}>{types.map(type => <option key={type}>{type}</option>)}</select></label><label>Units required<input type="number" min="1" max="10" value={unitsNeeded} onChange={e => setUnits(e.target.value)} /></label><label>Urgency<select value={urgency} onChange={e => setUrgency(e.target.value)}><option>CRITICAL</option><option>URGENT</option><option>NORMAL</option></select></label></div><button disabled={loading}>{loading ? 'Dispatching…' : 'Trigger emergency dispatch'}</button></form>;
}
function Radar({ request }) { const circles = [1, 5, 15]; return <div className="radar"><div className="hospital-dot">+</div>{circles.map((radius, index) => <div key={radius} className={`ring ring-${index} ${request.currentRadiusKm >= radius ? 'active' : ''}`}><span>{radius} km</span></div>)}{request.assignments.slice(0, 8).map((a, i) => <div className={`donor-dot ${a.status.toLowerCase()}`} style={{ left: `${18 + (i * 21) % 64}%`, top: `${23 + (i * 29) % 58}%` }} key={a.id} title={`${a.donorName}: ${a.status}`}/>)}</div>; }
function RequestCard({ request, token, refresh, setToast }) {
  const accepted = request.assignments.filter(a => ['ACCEPTED', 'ARRIVED', 'COMPLETED'].includes(a.status)).length;
  const action = async (suffix, success) => { try { await api(`/hospital/requests/${request.id}/${suffix}`, { method: 'POST' }, token); setToast(success); refresh(); } catch (err) { setToast(err.message); } };
  return <article className="request-card"><header><div><Badge tone={request.urgency === 'CRITICAL' ? 'red' : 'amber'}>{request.urgency}</Badge><h3>{request.bloodType} <span>blood needed</span></h3><p>{request.unitsNeeded} unit{request.unitsNeeded > 1 ? 's' : ''} requested · {new Date(request.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p></div><Badge tone={request.status === 'FULFILLED' ? 'green' : 'blue'}>{request.status}</Badge></header><div className="request-body"><Radar request={request}/><div className="metrics"><div><strong>{request.pinged}</strong><span>alerted</span></div><div><strong>{accepted}</strong><span>en route</span></div><div><strong>{request.fulfilledUnits}/{request.unitsNeeded}</strong><span>collected</span></div><p>Current dispatch perimeter: <b>{request.currentRadiusKm} km</b></p>{request.status === 'DISPATCHING' && <button className="secondary" onClick={() => action('escalate', 'Dispatch radius expanded.')}>Expand radius →</button>}{request.status === 'DISPATCHING' && <button className="link-button" onClick={() => action('close', 'Request marked fulfilled.')}>Close request</button>}</div></div><Roster entries={request.assignments}/></article>;
}
function Roster({ entries }) { return <div className="roster"><div className="roster-title">Dispatch roster <span>{entries.length} donors</span></div>{entries.length ? entries.map(entry => <div className="roster-row" key={entry.id}><span className="avatar">{entry.donorName.split(' ').map(x => x[0]).join('')}</span><b>{entry.donorName}</b><span>{entry.donorBloodType}</span><span>{entry.distanceKm} km</span><Badge tone={entry.status === 'COMPLETED' ? 'green' : entry.status === 'DECLINED' ? 'gray' : entry.status === 'PINGED' ? 'blue' : 'amber'}>{entry.status.replace('_', ' ')}</Badge></div>) : <p className="empty">No eligible nearby donors in this radius. Expand the search.</p>}</div>; }
function Dashboard({ session, onLogout }) {
  const [requests, setRequests] = useState([]); const [toast, setToast] = useState(''); const [checkin, setCheckin] = useState('');
  const refresh = () => api('/hospital/requests', {}, session.token).then(setRequests).catch(err => setToast(err.message));
  useEffect(() => { refresh(); const id = setInterval(refresh, 4000); return () => clearInterval(id); }, []);
  const create = request => { setRequests(previous => [request, ...previous]); setToast('SOS broadcast sent to the closest eligible donors.'); };
  async function scan(event) { event.preventDefault(); try { await api('/hospital/checkin', { method: 'POST', body: JSON.stringify({ token: checkin }) }, session.token); setCheckin(''); setToast('Donor checked in and reliability score credited.'); refresh(); } catch (err) { setToast(err.message); } }
  return <main className="app"><nav><div className="logo"><span>+</span> PULSE <em>DIAL</em></div><div className="hospital-name"><b>{session.hospital.name}</b><small>Verified · {session.hospital.licenseNumber}</small></div><button className="text-button" onClick={onLogout}>Sign out</button></nav>{toast && <div className="toast" onClick={() => setToast('')}>{toast} ×</div>}<section className="hero"><div><p className="eyebrow">EMERGENCY OPERATIONS</p><h1>Rapid donor dispatch</h1><p>Issue a verified SOS in seconds. The matching engine prioritizes eligible, active local donors.</p></div><div className="live"><span className="pulse"/> LIVE NETWORK<br/><b>{requests.filter(r => r.status === 'DISPATCHING').length} active emergency request{requests.filter(r => r.status === 'DISPATCHING').length === 1 ? '' : 's'}</b></div></section><section className="grid"><div className="panel"><h2>New emergency request</h2><NewRequest token={session.token} onCreated={create}/></div><form className="panel checkin" onSubmit={scan}><h2>Fast donor check-in</h2><p>Paste or scan the arrival token displayed in the donor app.</p><input placeholder="PULSE:assignment-id:token" value={checkin} onChange={e => setCheckin(e.target.value)} /><button>Verify arrival</button></form></section><section className="requests"><h2>Live dispatch radar</h2>{requests.length ? requests.map(request => <RequestCard key={request.id} request={request} token={session.token} refresh={refresh} setToast={setToast}/>) : <div className="blank"><div>♡</div><h3>No active alerts</h3><p>Create an emergency request to initiate a geofenced donor dispatch.</p></div>}</section></main>;
}
function App() { const [session, setSession] = useState(() => { try { return JSON.parse(localStorage.getItem('pulseHospital')); } catch { return null; } }); const login = value => { localStorage.setItem('pulseHospital', JSON.stringify(value)); setSession(value); }; const logout = () => { localStorage.removeItem('pulseHospital'); setSession(null); }; return session ? <Dashboard session={session} onLogout={logout}/> : <Login onLogin={login}/>; }
createRoot(document.getElementById('root')).render(<App/>);
